### ISSUE TITLE
vietoje TreeSet<String> naudoti Set<String>

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#10]
https://github.com/mariuslit/Zodynas_2_sample/blob/313d5872e200670bf070ec00ab8a0f1044fa7ea7/src/sample/Controller.java#L181

**Comment by mariuslit** [comment]
Andriau jeigu padarau Set nebeveikia variant.first() metodas, 
man reikia kad paimtų parmają sarašo reikšmę pagal abėcėlę

**Comment by andriusbaltrunas** [comment]
Paikurkite Utils klase kur is bet kokios paduotos kolekcijos grazintu pirma elementa ten kur jum reikia. Tada galesite naudoti Set
