### ISSUE TITLE
kam naudojat replace? 

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#12]
https://github.com/mariuslit/Zodynas_2_sample/blob/313d5872e200670bf070ec00ab8a0f1044fa7ea7/src/sample/ControllerR.java#L52

**Comment by mariuslit** [comment]
replace tik pataiso dalį žodyno pavadinimo, jis neatlieka darbo iki galo, todėl ištryniau
