### ISSUE TITLE
Cia uzdavo Sena controlleri, kam to reikia?

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#16]
https://github.com/mariuslit/Zodynas_2_sample/blob/313d5872e200670bf070ec00ab8a0f1044fa7ea7/src/sample/ControllerR.java#L155

**Comment by mariuslit** [comment]
padariau:
Controller.closeStageR();
metodą closeStageR(); pakaičiau į static
