### ISSUE TITLE
Cia nera logikos kam jus istrinat tarpus ir ziurit ar nera tarpu?

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#28]
https://github.com/mariuslit/Zodynas_2_sample/blob/c5f023c022ad92b25f85531e9fa7105e8ca12aa5/src/sample/ControllerR.java#L57

**Comment by mariuslit** [comment]
// patikrina ar vartotojas neįrašė tuščio pavadinimo - vieno ar kelių tuščių tarpų.
