### ISSUE TITLE
Jei nurodai masyvui kokio typo jis yra toki ir deklaruok metode, kad nebutu klaidu po to Map<String, String>

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#4]
https://github.com/mariuslit/Zodynas_2_sample/blob/0d3dbffb0b083e53dd4ad1f3fb5bad8a30c43954/src/sample/ReadWriteData/ReadWriteData.java#L15

**Comment by mariuslit** [comment]
atlikta
