### ISSUE TITLE
Nelabai suprantu kam tu keiti elementa i enter po to vel i nauja eilute irasanat?

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#5]
https://github.com/mariuslit/Zodynas_2_sample/blob/0d3dbffb0b083e53dd4ad1f3fb5bad8a30c43954/src/sample/ReadWriteData/ReadWriteData.java#L23

**Comment by mariuslit** [comment]
nes .txt failo struktūra puikiai atitinka TreeMap struktūrą, viena eilutė yra:
[Key(Žodis) -->> Value(Vertimas)]
problema ta, kad "Vertimas" gali būti ir iš kelių eilučių, toks užsakovo pageidavimas :)
todėl kode "Vertimas" sukarpomas su "\n" simboliu, kuris tinka atspausdinimui į TextField ir Label
bet "\n" netinka įrašymui į failą, nes išdarko failo struktūrą - prideda neteisingų eilučių
tam ir keičiu "\n" į " < enter > " tik dėl įrašymo į failą, o nuskaitant darau priešingą veiksmą - atkeičiu atgal.

ir niekaip nesugalvoju, kaip observableList čia gali būti naudingas?

kaip supratau observableList galima patogiai naudoti nuskaitant ir įrašant į ListView ar TableView nenaudojant ciklų, tai ten ir pritaikysiu.

nebent turi kitokių minčių?
