### ISSUE TITLE
Kodel tu kelis kartus nuskaitai ta pati faila?  Nuskaitymas turi vykti tik tada kai programa pradeda darba

### ISSUE THREAD

**Issue by andriusbaltrunas** [mariuslit/Zodynas_2_sample#9]
https://github.com/mariuslit/Zodynas_2_sample/blob/0d3dbffb0b083e53dd4ad1f3fb5bad8a30c43954/src/sample/Controller.java#L158

**Comment by mariuslit** [comment]
šis metodas nuskaito failą tik:
1. inicializacijos metu
2. kai pasirenkamas kitas žodynas
